# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = true
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "forge-build"
  script = "script"
  # solc = "0.8.19"
  src = "contracts"
  test = "test"
libs = ["node_modules", "lib"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4



[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 140
  multiline_func_header = "params_first"
  number_underscore = "thousands"
  sort_imports = true
  quote_style = "single"
  contract_new_lines = false
  override_spacing = true
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]

  sepolia = "https://bartio.rpc.berachain.com/"
